package entidade;
// Generated 04/10/2015 19:28:26 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Auditoria generated by hbm2java
 */
@Entity
@Table(name = "auditoria", schema = "public"
)
public class Auditoria implements java.io.Serializable {

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    @Column(name = "usuario", nullable = false, length = 200)
    private String usuario;
    @Column(name = "dados", nullable = false, length = 200)
    private String dados;
    @Column(name = "tabela", nullable = false, length = 45)
    private String tabela;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "data", nullable = false, length = 29)
    private Date data;
    @Column(name = "operacao", nullable = false, length = 45)
    private String operacao;

    public Auditoria() {
    }

    public int getIdauditoria() {
        return this.id;
    }

    public void setIdauditoria(int id) {
        this.id = id;
    }

    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getDados() {
        return this.dados;
    }

    public void setDados(String dados) {
        this.dados = dados;
    }

    public String getTabela() {
        return this.tabela;
    }

    public void setTabela(String tabela) {
        this.tabela = tabela;
    }

    public Date getData() {
        return this.data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    public String getOperacao() {
        return this.operacao;
    }

    public void setOperacao(String operacao) {
        this.operacao = operacao;
    }

}
