package entidade;
// Generated 17/08/2015 19:54:52 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Cidade generated by hbm2java
 */


@Entity

@Table(name = "cidade", schema = "public")
public class Cidade implements java.io.Serializable {
    
    @Id
    @Column(name = "idCidade")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int idcidade;
    @Column(name = "descricao", nullable = false, length = 45)
    private String descricao;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "estado_idestado", nullable = false)
    private Estado estado;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cidade")
    private Set<Endereco> enderecos = new HashSet(0);

    public Cidade() {
    }

    public Cidade(int idcidade, Estado estado, String descricao) {
        this.idcidade = idcidade;
        this.estado = estado;
        this.descricao = descricao;
    }

   
    public int getIdcidade() {
        return this.idcidade;
    }

    public void setIdcidade(int idcidade) {
        this.idcidade = idcidade;

    }

    public Estado getEstado() {
        return this.estado;
    }

    public void setEstado(Estado estado) {
        this.estado = estado;

    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;

    }

    public Set getEnderecos() {
        return this.enderecos;
    }

    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }

}
