package entidade;
// Generated 17/08/2015 19:54:52 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Funcao generated by hbm2java
 */
@Entity
@Table(name = "funcao", schema = "public")
public class Funcao implements java.io.Serializable {

    @Id
    @Column(name = "idfuncao")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    private int idfuncao;
    @Column(name = "descricao", nullable = false, length = 45)
    private String descricao;
    
    public Funcao() {
    }

    public Funcao(int idfuncao, String descricao) {
        this.idfuncao = idfuncao;
        this.descricao = descricao;
    }

    public Funcao(int idfuncao, String descricao, Set funcionarios) {
        this.idfuncao = idfuncao;
        this.descricao = descricao;
       
    }

    public int getIdfuncao() {
        return this.idfuncao;
    }

    public void setIdfuncao(int idfuncao) {
        this.idfuncao = idfuncao;
    }

    
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

}
