package entidade;
// Generated 17/08/2015 19:54:52 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Parcelaspagamento generated by hbm2java
 */
@Entity
@Table(name="parcelaspagamento"
    ,schema="public"
)
public class Parcelaspagamento  implements java.io.Serializable {

@Id
    @Column(name = "idparcelaspagamento")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     private int idparcelaspagamento;
 @Temporal(TemporalType.DATE)
    @Column(name="dt_pagamento", nullable=false, length=13)
     private Date dtPagamento;
  @Temporal(TemporalType.DATE)
    @Column(name="dt_vencimento", nullable=false, length=13)
     private Date dtVencimento;
    @Column(name="liquidado", precision=11)  
    
  private BigDecimal liquidado;
       @Column(name="valor", nullable=false, precision=11)
     private BigDecimal valor;
     
    public Parcelaspagamento() {
    }

	
    public Parcelaspagamento(int idparcelaspagamento, Date dtPagamento, Date dtVencimento, BigDecimal valor) {
        this.idparcelaspagamento = idparcelaspagamento;
        this.dtPagamento = dtPagamento;
        this.dtVencimento = dtVencimento;
        this.valor = valor;
    }
    public Parcelaspagamento(int idparcelaspagamento, Date dtPagamento, Date dtVencimento, BigDecimal liquidado, BigDecimal valor, Set locacaos) {
       this.idparcelaspagamento = idparcelaspagamento;
       this.dtPagamento = dtPagamento;
       this.dtVencimento = dtVencimento;
       this.liquidado = liquidado;
       this.valor = valor;
       
    }
   
    
    public int getIdparcelaspagamento() {
        return this.idparcelaspagamento;
    }
    
    public void setIdparcelaspagamento(int idparcelaspagamento) {
        this.idparcelaspagamento = idparcelaspagamento;
    }

   
    public Date getDtPagamento() {
        return this.dtPagamento;
    }
    
    public void setDtPagamento(Date dtPagamento) {
        this.dtPagamento = dtPagamento;
    }

   
    public Date getDtVencimento() {
        return this.dtVencimento;
    }
    
    public void setDtVencimento(Date dtVencimento) {
        this.dtVencimento = dtVencimento;
    }

    
    public BigDecimal getLiquidado() {
        return this.liquidado;
    }
    
    public void setLiquidado(BigDecimal liquidado) {
        this.liquidado = liquidado;
    }
  
 
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }



}


