package entidade;
// Generated 04/10/2015 19:28:26 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Permissao generated by hbm2java
 */
@Entity
@Table(name = "permissao", schema = "public"
)
public class Permissao implements java.io.Serializable {

    @Id
    @Column(name = "idPermissao")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int idpermissao;
    @Column(name = "idfuncao")
    private int idfuncao;
    @Column(name = "idpessoa")
    private int idpessoa;
    @Column(name = "idtela", nullable = false)
    private int idtela;
    @Column(name = "ler", nullable = false)
    private boolean ler;
    @Column(name = "inserir", nullable = false)
    private boolean inserir;
    @Column(name = "editar", nullable = false)
    private boolean editar;
    @Column(name = "inativar", nullable = false)
    private boolean inativar;

    public Permissao() {
    }

    public Permissao(int idpermissao, int tela, boolean ler, boolean inserir, boolean editar, boolean inativar) {
        this.idpermissao = idpermissao;
        this.idtela = tela;
        this.ler = ler;
        this.inserir = inserir;
        this.editar = editar;
        this.inativar = inativar;
    }

    public Permissao(int idpermissao, int funcao, int pessoa, int tela, boolean ler, boolean inserir, boolean editar, boolean inativar) {
        this.idpermissao = idpermissao;
        this.idfuncao = funcao;
        this.idpessoa = pessoa;
        this.idtela = tela;
        this.ler = ler;
        this.inserir = inserir;
        this.editar = editar;
        this.inativar = inativar;
    }

    public int getIdpermissao() {
        return this.idpermissao;
    }

    public void setIdpermissao(int idpermissao) {
        this.idpermissao = idpermissao;
    }

    public int getIdfuncao() {
        return this.idfuncao;
    }

    public void setIdFuncao(int idfuncao) {
        this.idfuncao = idfuncao;
    }

    public int getIdpessoa() {
        return this.idpessoa;
    }

    public void setIdpessoa(int idpessoa) {
        this.idpessoa = idpessoa;
    }

    public int getIdtela() {
        return this.idtela;
    }

    public void setIdtela(int idtela) {
        this.idtela = idtela;
    }

    public boolean isLer() {
        return this.ler;
    }

    public void setLer(boolean ler) {
        this.ler = ler;
    }

    public boolean isInserir() {
        return this.inserir;
    }

    public void setInserir(boolean inserir) {
        this.inserir = inserir;
    }

    public boolean isEditar() {
        return this.editar;
    }

    public void setEditar(boolean editar) {
        this.editar = editar;
    }

    public boolean isInativar() {
        return this.inativar;
    }

    public void setInativar(boolean inativar) {
        this.inativar = inativar;
    }

}
