package entidade;
// Generated 17/08/2015 19:54:52 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reserva generated by hbm2java
 */
@Entity
@Table(name = "reserva", schema = "public"
)
public class Reserva implements java.io.Serializable {

    @Id
    @Column(name = "idreserva")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int idreserva;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cliente_pessoa_idpessoa", nullable = false)
    private Cliente cliente;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "funcionario_pessoa_idpessoa", nullable = false)
    private Funcionario funcionario;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "veiculo_idveiculo", nullable = false)
    private Veiculo veiculo;
    @Temporal(TemporalType.DATE)
    @Column(name = "dt_reserva", nullable = false, length = 13)
    private Date dtReserva;
    @Temporal(TemporalType.DATE)
    @Column(name = "dt_locacao", nullable = false, length = 13)
    private Date dtlocacao;
    @Column(name = "dtdevolucao", nullable = false)
    private Date dtdevolucao;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "reserva")
    private Set<Locacao> locacaos = new HashSet(0);

    public Reserva() {
    }

    public Reserva(int idreserva, Cliente cliente, Funcionario funcionario, Veiculo veiculo, Date dtReserva, Date dtlocacao, Date dtdevolucao) {
        this.idreserva = idreserva;
        this.cliente = cliente;
        this.funcionario = funcionario;
        this.veiculo = veiculo;
        this.dtReserva = dtReserva;
        this.dtlocacao = dtlocacao;
        this.dtdevolucao = dtdevolucao;
    }

    public Reserva(int idreserva, entidade.Cliente cliente, entidade.Funcionario funcionario, Veiculo veiculo, Date dtReserva, Date dtlocacao, Date dtdevolucao, Set locacaos) {
        this.idreserva = idreserva;
        this.cliente = cliente;
        this.funcionario = funcionario;
        this.veiculo = veiculo;
        this.dtReserva = dtReserva;
        this.dtlocacao = dtlocacao;
        this.dtdevolucao = dtdevolucao;
        this.locacaos = locacaos;
    }

    public int getIdreserva() {
        return this.idreserva;
    }

    public void setIdreserva(int idreserva) {
        this.idreserva = idreserva;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Funcionario getFuncionario() {
        return this.funcionario;
    }

    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

    public Veiculo getVeiculo() {
        return this.veiculo;
    }

    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
    }

    public Date getDtReserva() {
        return this.dtReserva;
    }

    public void setDtReserva(Date dtReserva) {
        this.dtReserva = dtReserva;
    }

    public Date getDtLocacao() {
        return this.dtlocacao;
    }

    public void setDtLocacao(Date dtlocacao) {
        this.dtlocacao = dtlocacao;
    }

    public Date getDtDevolucao() {
        return this.dtdevolucao;
    }

    public void setDtDevolucao(Date dtdevolucao) {
        this.dtdevolucao = dtdevolucao;
    }

    public Set getLocacaos() {
        return this.locacaos;
    }

    public void setLocacaos(Set locacaos) {
        this.locacaos = locacaos;
    }

}
