/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import conf.ComboItens;
import conf.CombosDAO;
import conf.DAO;
import conf.Formatacao;
import conf.HibernateUtil;
import conf.Popula;
import conf.Utility;
import entidade.Cidade;
import entidade.Cliente;
import entidade.Contato;
import entidade.Contatopessoas;
import entidade.Endereco;
import entidade.Estado;
import entidade.Pessoa;
import entidade.Pessoafisica;
import entidade.Pessoajuridica;
import entidade.Tipocontato;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.apache.log4j.Logger;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Daiane
 */
public class IfCliente extends javax.swing.JInternalFrame {

    private org.apache.log4j.Logger logger = Logger.getLogger(DgLogin.class.getName());
    private int codPessoa = 0;
    private int codEndereco = 0;
    private int codCidade = 0;
    private int codContato = 0;
    private String fazer = "";

    /**
     * Creates new form IfCliente
     */
    public IfCliente() {
        initComponents();
        Utility.permit(btNovo, btSalvar, btEditar, null, this);
        habilitaCamposPfisica(false);
        habilitaCamposPjuridica(false);
        this.pesquisa();
        jTabbedPane1StateChanged(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpCadastroCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfTelefone1 = new javax.swing.JFormattedTextField();
        tfDataCadastro = new javax.swing.JFormattedTextField();
        lbCPFouCNPJ = new javax.swing.JLabel();
        tfCPF = new javax.swing.JFormattedTextField();
        lbRGouIE = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfBairro = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfCEP = new javax.swing.JFormattedTextField();
        tfCEP = Formatacao.getCEP();
        tfCidade = new javax.swing.JTextField();
        rbPessoaFisica = new javax.swing.JRadioButton();
        rbPessoaJuridica = new javax.swing.JRadioButton();
        btPCidade = new javax.swing.JButton();
        tfComplemento = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfUF = new javax.swing.JTextField();
        tfRG = new javax.swing.JFormattedTextField();
        tfRG = Formatacao.getRG();
        tfCNPJ = new javax.swing.JFormattedTextField();
        tfCNPJ = Formatacao.getCNPJ();
        tfIE = new javax.swing.JFormattedTextField();
        tfCNPJ = Formatacao.getCNPJ();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfPesquisa = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btFechar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setTitle("Cadastro de clientes");

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jpCadastroCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpCadastroClienteFocusGained(evt);
            }
        });

        jLabel1.setText("Data cadastro:");

        lbNome.setText("Nome:*");

        jLabel4.setText("Telefone 1:*");

        try {
            tfTelefone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefone1 = Formatacao.getTelefone();

        tfDataCadastro.setEnabled(false);

        lbCPFouCNPJ.setText("CPF:*");

        try {
            tfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCPF = Formatacao.getCPF();

        lbRGouIE.setText("RG:*");

        jLabel7.setText("Endereço*:");

        jLabel8.setText("Bairro*:");

        jLabel9.setText("Cidade*:");

        jLabel10.setText("Estado*:");

        jLabel15.setText("CEP*:");

        tfCidade.setEditable(false);
        tfCidade.setPreferredSize(new java.awt.Dimension(150, 20));

        buttonGroup2.add(rbPessoaFisica);
        rbPessoaFisica.setText("Pessoa Física");
        rbPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPessoaFisicaActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbPessoaJuridica);
        rbPessoaJuridica.setText("Pessoa Jurídica");
        rbPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPessoaJuridicaActionPerformed(evt);
            }
        });

        btPCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/procurar_20x20.png"))); // NOI18N
        btPCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPCidadeActionPerformed(evt);
            }
        });

        jLabel11.setText("Complemento:");

        jLabel2.setText("Cnpj:*");

        jLabel5.setText("IE:*");

        tfUF.setEditable(false);
        tfUF.setPreferredSize(new java.awt.Dimension(150, 20));

        tfRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tfRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRGActionPerformed(evt);
            }
        });
        tfRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfRGKeyTyped(evt);
            }
        });

        tfCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        tfCNPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCNPJFocusLost(evt);
            }
        });
        tfCNPJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCNPJKeyTyped(evt);
            }
        });

        tfIE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        tfIE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfIEFocusLost(evt);
            }
        });
        tfIE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIEKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jpCadastroClienteLayout = new javax.swing.GroupLayout(jpCadastroCliente);
        jpCadastroCliente.setLayout(jpCadastroClienteLayout);
        jpCadastroClienteLayout.setHorizontalGroup(
            jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroClienteLayout.createSequentialGroup()
                .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadastroClienteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCadastroClienteLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfDataCadastro)
                                .addGap(27, 27, 27)
                                .addComponent(rbPessoaFisica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbPessoaJuridica)
                                .addGap(146, 146, 146))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCadastroClienteLayout.createSequentialGroup()
                                .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpCadastroClienteLayout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfCNPJ)
                                            .addComponent(tfCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                        .addGap(20, 20, 20)
                                        .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jpCadastroClienteLayout.createSequentialGroup()
                                                .addComponent(lbRGouIE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfRG, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jpCadastroClienteLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfIE, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jpCadastroClienteLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(1, 1, 1)
                                        .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 8, Short.MAX_VALUE))
                            .addGroup(jpCadastroClienteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpCadastroClienteLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfUF, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btPCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpCadastroClienteLayout.createSequentialGroup()
                                        .addComponent(lbNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpCadastroClienteLayout.createSequentialGroup()
                                        .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jpCadastroClienteLayout.createSequentialGroup()
                                                .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jpCadastroClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCPFouCNPJ)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCadastroClienteLayout.setVerticalGroup(
            jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastroClienteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPessoaFisica)
                    .addComponent(rbPessoaJuridica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(tfTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadastroClienteLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lbCPFouCNPJ))
                    .addGroup(jpCadastroClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbRGouIE)
                            .addComponent(tfRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btPCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfUF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro Clientes", jpCadastroCliente);

        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2FocusGained(evt);
            }
        });

        jLabel3.setText("Busca");

        tfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyReleased(evt);
            }
        });

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/procurar_20x20.png"))); // NOI18N
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "CPF", "RG", "Telefone", "Endereço", "Cidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbClientes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta Clientes", jPanel2);

        jToolBar1.setRollover(true);

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/novo_32x32.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btNovo);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar_32x32.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jToolBar1.add(btSalvar);

        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/bEditar.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btEditar);
        jToolBar1.add(jSeparator1);

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/fechar_32x32.png"))); // NOI18N
        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        jToolBar1.add(btFechar);

        jLabel16.setText("* Campos obrigatórios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (tfNome.getText().trim().length() > 0) {

            Endereco endereco = new Endereco();
            endereco.setIdendereco(codEndereco);
            endereco.setDescricao(tfEndereco.getText());
            endereco.setBairro(tfBairro.getText());
            endereco.setCep(tfCEP.getText());
            endereco.setComplemento(tfComplemento.getText());
            Object[] oCidade;
            oCidade = (Object[]) Popula.retornaCidade(codCidade);
            List<Cidade> l = (List<Cidade>) oCidade[0];
            for (Cidade lin : l) {
                Cidade c = lin;
                endereco.setCidade(c);
            }

            Pessoa pessoa = new Pessoa();
            pessoa.setIdpessoa(codPessoa);
            pessoa.setNome(tfNome.getText());
            pessoa.setEndereco(endereco);

            Cliente cliente = new Cliente();
            cliente.setDtCadastro(Formatacao.converteParaDataAMD(tfDataCadastro.getText()));

            Pessoafisica pFisica = new Pessoafisica();
            Pessoajuridica pJuridica = new Pessoajuridica();
            if (rbPessoaFisica.isSelected()) {
                pFisica.setCpf(tfCPF.getText());
                pFisica.setRg(tfRG.getText());
            }
            if (rbPessoaJuridica.isSelected()) {
                pJuridica.setCnpj(tfCNPJ.getText());
                pJuridica.setInscricaoest(tfIE.getText());
            }

            DAO.salvarEndereco(endereco);
            DAO.salvarPessoa(pessoa);

            int idpes = pessoa.getIdpessoa();
            Contato contato = new Contato();
            contato.setIdcontato(codContato);
            contato.setDescricao(tfTelefone1.getText());
            contato.setPessoa(pessoa);

            Object[] objectt;
            objectt = (Object[]) Popula.retornaTipoContato(1);//para telefone
            List<Tipocontato> list = (List<Tipocontato>) objectt[0];
            for (Tipocontato lin : list) {
                Tipocontato tc = lin;
                contato.setTipocontato(tc);
                DAO.salvarContato(contato, fazer);
            }

            cliente.setPessoaIdpessoa(idpes);
            cliente.setPessoa(pessoa);
            DAO.salvarCliente(cliente, fazer);

            if (rbPessoaFisica.isSelected()) {
                pFisica.setPessoaIdpessoa(idpes);
                pFisica.setPessoa(pessoa);
                DAO.salvarPessoaFisica(pFisica, fazer);
            }
            if (rbPessoaJuridica.isSelected()) {
                pJuridica.setPessoaIdpessoa(idpes);
                pJuridica.setPessoa(pessoa);
                DAO.salvarPessoaJuridica(pJuridica, fazer);
            }
            pesquisa();
            habilitaCamposPfisica(false);
            habilitaCamposPjuridica(false);

        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios!");
        }

    }//GEN-LAST:event_btSalvarActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        pesquisa();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void tfPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyReleased
        pesquisa();
    }//GEN-LAST:event_tfPesquisaKeyReleased

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        rbPessoaFisica.setSelected(true);

        //rbPessoaFisica.isSelected();
        if (rbPessoaFisica.isSelected()) {
            habilitaCamposPfisica(true);
        } else {
            habilitaCamposPjuridica(true);
        }
        jTabbedPane1.setSelectedIndex(0);
        btNovo.setEnabled(false);
        btSalvar.setEnabled(true);
        tfDataCadastro.setText(Formatacao.getDataAtual());
        codPessoa = 0;
        codEndereco = 0;
        codContato = 0;
        fazer = "salvar";
    }//GEN-LAST:event_btNovoActionPerformed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained

    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained

    }//GEN-LAST:event_jPanel2FocusGained

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (jTabbedPane1.getSelectedIndex() == 1) {
            habilitaCamposPfisica(false);
            habilitaCamposPjuridica(false);
            pesquisa();
            btSalvar.setEnabled(false);
            btEditar.setEnabled(true);
            btNovo.setEnabled(true);
        } else if (jTabbedPane1.getSelectedIndex() == 0) {
            btSalvar.setEnabled(false);
            btEditar.setEnabled(false);
            btNovo.setEnabled(true);
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed

        if (jTabbedPane1.getSelectedIndex() == 1) {
            if (tbClientes.getSelectedRow() >= 0) {
                String cod = String.valueOf(tbClientes.getValueAt(tbClientes.getSelectedRow(), 0));
                int codigo = Integer.parseInt(cod);
                Object[] object;
                Object[] oContatos;
                object = (Object[]) Popula.retornaDadosPessoas(codigo);
                List<Cliente> lc = (List<Cliente>) object[3];
                for (Cliente linc : lc) {

                    tfDataCadastro.setText(Formatacao.ajustaDataDMA(String.valueOf(linc.getDtCadastro())));
                    Pessoa p = linc.getPessoa();
                    codPessoa = p.getIdpessoa();
                    tfNome.setText(p.getNome());

                    oContatos = (Object[]) Popula.retornaDadosPessoas(codigo);
                    List<Contato> lcontatos = (List<Contato>) oContatos[5];
                    for (Contato lincont : lcontatos) {
                        String tel1 = "";
                        tel1 = lincont.getDescricao();
                        tfTelefone1.setText(tel1);
                        System.out.println("tel1:" + tel1);
                        codContato = lincont.getIdcontato();
                    }
                    Pessoafisica pf = linc.getPessoa().getPessoafisica();
                    if (pf != null) {
                        tfCPF.setText(pf.getCpf());
                        tfRG.setText(pf.getRg());
                        rbPessoaFisica.setSelected(true);
                        habilitaCamposPfisica(true);
                    }
                    Pessoajuridica pj = linc.getPessoa().getPessoajuridica();
                    if (pj != null) {
                        tfCNPJ.setText(pj.getCnpj());
                        tfIE.setText(pj.getInscricaoest());
                        rbPessoaJuridica.setSelected(true);
                        habilitaCamposPjuridica(true);
                    }
                    Endereco e = linc.getPessoa().getEndereco();
                    tfEndereco.setText(e.getDescricao());
                    tfBairro.setText(e.getBairro());
                    tfCEP.setText(e.getCep());
                    tfUF.setText(e.getCidade().getEstado().getUf());
                    tfCidade.setText(e.getCidade().getDescricao());
                    codCidade = e.getCidade().getIdcidade();
                    tfComplemento.setText(e.getComplemento());
                    codEndereco = e.getIdendereco();
                }
                jTabbedPane1.setSelectedIndex(0);
                pesquisa();
                btNovo.setEnabled(false);
                btSalvar.setEnabled(true);
                tfNome.requestFocus();
                fazer = "atualizar";
            } else {
                JOptionPane.showMessageDialog(null, "Selecione algum registro!");
            }
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void jpCadastroClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpCadastroClienteFocusGained

    }//GEN-LAST:event_jpCadastroClienteFocusGained

    private void tbClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClientesMouseClicked
        if (evt.getClickCount() > 1) {
            btEditarActionPerformed(null);
        }
    }//GEN-LAST:event_tbClientesMouseClicked

    private void btPCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPCidadeActionPerformed
        DgConsultaCidade tela = new DgConsultaCidade(this, null, null);
        tela.setVisible(true);
    }//GEN-LAST:event_btPCidadeActionPerformed

    private void rbPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPessoaFisicaActionPerformed
        habilitaCamposPfisica(true);
        if (btNovo.isEnabled()) {
            btNovoActionPerformed(null);
        }
    }//GEN-LAST:event_rbPessoaFisicaActionPerformed

    private void rbPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPessoaJuridicaActionPerformed
        habilitaCamposPjuridica(true);
        if (btNovo.isEnabled()) {
            btNovoActionPerformed(null);
        }
    }//GEN-LAST:event_rbPessoaJuridicaActionPerformed

    private void tfRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRGActionPerformed

    private void tfRGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRGKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfRGKeyTyped

    private void tfCNPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCNPJFocusLost

    }//GEN-LAST:event_tfCNPJFocusLost

    private void tfCNPJKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCNPJKeyTyped

    }//GEN-LAST:event_tfCNPJKeyTyped

    private void tfIEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIEFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIEFocusLost

    private void tfIEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIEKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIEKeyTyped

    public void habilitaCamposPfisica(Boolean tf) {
        if (tf == false) {
            limpaCampos();
            btNovo.setEnabled(true);
            btSalvar.setEnabled(false);
        }

        tfNome.setEnabled(tf);
        tfTelefone1.setEnabled(tf);
        tfCPF.setEnabled(tf);
        tfRG.setEnabled(tf);
        tfCNPJ.setEnabled(false);
        tfIE.setEnabled(false);
        tfEndereco.setEnabled(tf);
        tfBairro.setEnabled(tf);
        tfCEP.setEnabled(tf);
        tfUF.setEnabled(false);
        tfCidade.setEnabled(false);
        tfComplemento.setEnabled(tf);
        btPCidade.setEnabled(tf);
    }

    public void habilitaCamposPjuridica(Boolean tf) {
        if (tf == false) {
            limpaCampos();
            btNovo.setEnabled(true);
            btSalvar.setEnabled(false);
        }
        tfNome.setEnabled(tf);
        tfTelefone1.setEnabled(tf);
        tfCPF.setEnabled(false);
        tfRG.setEnabled(false);
        tfCNPJ.setEnabled(tf);
        tfIE.setEnabled(tf);
        tfEndereco.setEnabled(tf);
        tfBairro.setEnabled(tf);
        tfCEP.setEnabled(tf);
        tfUF.setEnabled(false);
        tfCidade.setEnabled(false);
        tfComplemento.setEnabled(tf);
        btPCidade.setEnabled(tf);
    }

    public void limpaCampos() {
        tfDataCadastro.setText(Formatacao.getDataAtual());
        tfNome.setText("");
        tfTelefone1.setText("");
        tfCPF.setText("");
        tfRG.setText("");
        tfCNPJ.setText("");
        tfIE.setText("");
        tfEndereco.setText("");
        tfBairro.setText("");
        tfCEP.setText("");
        tfCidade.setText("");
        tfComplemento.setText("");
        btPCidade.setText("");
        tfUF.setText("");
        rbPessoaJuridica.setSelected(false);
        rbPessoaFisica.setSelected(false);
        Formatacao.reformatarCnpj(tfCNPJ);
        Formatacao.reformatarIe(tfIE);
        Formatacao.reformatarCEP(tfCEP);
        Formatacao.reformatarTelefone(tfTelefone1);
        Formatacao.reformatarRG(tfRG);
        Formatacao.reformatarCpf(tfCPF);
    }

    public void pesquisa() {
        int cod = 0;
        if (tfPesquisa.getText().length() > 0 && tfPesquisa.getText().matches("[0-9]")) {
            cod = Integer.parseInt(tfPesquisa.getText());
        }
        Popula.popularTabelaCliente(cod, tfPesquisa.getText(), tbClientes);
    }

    public void defineCodigoCidade(int cod, String nome, String uf) {
        codCidade = cod;
        tfCidade.setText(nome);
        tfUF.setText(uf);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPCidade;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel jpCadastroCliente;
    private javax.swing.JLabel lbCPFouCNPJ;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbRGouIE;
    private javax.swing.JRadioButton rbPessoaFisica;
    private javax.swing.JRadioButton rbPessoaJuridica;
    private javax.swing.JTable tbClientes;
    private javax.swing.JFormattedTextField tfBairro;
    private javax.swing.JFormattedTextField tfCEP;
    private javax.swing.JFormattedTextField tfCNPJ;
    private javax.swing.JFormattedTextField tfCPF;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JFormattedTextField tfComplemento;
    private javax.swing.JFormattedTextField tfDataCadastro;
    private javax.swing.JFormattedTextField tfEndereco;
    private javax.swing.JFormattedTextField tfIE;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPesquisa;
    private javax.swing.JFormattedTextField tfRG;
    private javax.swing.JFormattedTextField tfTelefone1;
    private javax.swing.JTextField tfUF;
    // End of variables declaration//GEN-END:variables
}
