/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import conf.ComboItens;
import conf.CombosDAO;
import conf.DAO;
import conf.Formatacao;
import conf.Popula;
import conf.Utility;
import conf.limpaCampos;
import entidade.Contato;
import entidade.Funcionario;
import entidade.Pessoa;
import entidade.Populartabelacliente;
import entidade.Populartabelafornecedor;
import entidade.Populartabelafuncionario;
import entidade.Tipocontato;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.apache.log4j.Logger;

/**
 *
 * @author Daiane
 */
public class IfContatos extends javax.swing.JInternalFrame {

    private org.apache.log4j.Logger logger = Logger.getLogger(DgLogin.class.getName());
    private int codCliente = 0;
    private int codFuncionario = 0;
    private int codFornecedor = 0;

    /**
     * Creates new form IfReservaVeiculos
     */
    public IfContatos() {
        initComponents();
        Utility.permit(btNovo, btSalvar, null, null, this);
        habilitaCamposCliente(false);
        habilitaCamposFornecedor(false);
        habilitaCamposFuncionario(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btFechar1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelClienteTotal = new javax.swing.JPanel();
        jpCliente = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tfNomeCliente = new javax.swing.JTextField();
        tfRGCli = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfEnderecoCli = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfTelefoneCli = new javax.swing.JTextField();
        tfBairroCli = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfCidadeCli = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btPCliente = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        tfCPFCli = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCliente = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jpFornecedor = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tfRazaoSocial = new javax.swing.JTextField();
        tfCNPJForn = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tfEnderecoForn = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tfTelefoneForn = new javax.swing.JTextField();
        tfBairroForn = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tfCidadeForn = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        btPFornecedor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbFornecedor = new javax.swing.JTable();
        jPanelFuncTotal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFuncionario = new javax.swing.JTable();
        jpFuncionario = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tfNomeFunc = new javax.swing.JTextField();
        tfRGFunc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfFuncaoFunc = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tfTelefoneFunc = new javax.swing.JTextField();
        tfLoginFunc = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        btPFuncionario = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        tfCPFFunc = new javax.swing.JTextField();
        jpContatoFunc = new javax.swing.JPanel();
        btAdicionarFunc = new javax.swing.JButton();
        cbTipoFunc = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btExcluirFunc = new javax.swing.JButton();
        tfDescricaoContatoFunc = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Contatos");

        jLabel20.setText("* Campos obrigatórios");

        jToolBar1.setRollover(true);

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/novo_32x32.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btNovo);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar_32x32.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jToolBar1.add(btSalvar);
        jToolBar1.add(jSeparator1);

        btFechar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/fechar_32x32.png"))); // NOI18N
        btFechar1.setText("Fechar");
        btFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFechar1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btFechar1);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jPanelClienteTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanelClienteTotalFocusGained(evt);
            }
        });

        jpCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Cliente*"));

        jLabel10.setText("Nome:");

        tfNomeCliente.setEditable(false);

        tfRGCli.setEditable(false);

        jLabel11.setText("RG:");

        tfEnderecoCli.setEditable(false);

        jLabel12.setText("Endereço:");

        jLabel13.setText("Telefone:");

        tfTelefoneCli.setEditable(false);

        tfBairroCli.setEditable(false);

        jLabel14.setText("Bairro:");

        tfCidadeCli.setEditable(false);

        jLabel15.setText("Cidade:");

        btPCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/procurar_20x20.png"))); // NOI18N
        btPCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPClienteActionPerformed(evt);
            }
        });

        jLabel17.setText("CPF:");

        tfCPFCli.setEditable(false);

        javax.swing.GroupLayout jpClienteLayout = new javax.swing.GroupLayout(jpCliente);
        jpCliente.setLayout(jpClienteLayout);
        jpClienteLayout.setHorizontalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10)
                        .addComponent(jLabel12))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClienteLayout.createSequentialGroup()
                        .addComponent(tfNomeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jpClienteLayout.createSequentialGroup()
                        .addComponent(tfRGCli, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCPFCli, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTelefoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpClienteLayout.createSequentialGroup()
                        .addComponent(tfBairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCidadeCli))
                    .addComponent(tfEnderecoCli)))
        );
        jpClienteLayout.setVerticalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpClienteLayout.createSequentialGroup()
                        .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(tfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfRGCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(tfTelefoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfCPFCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(tfEnderecoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfBairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addComponent(jLabel14)))
        );

        tbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Descrição Contato", "Tipo", "Pessoa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCliente);

        javax.swing.GroupLayout jPanelClienteTotalLayout = new javax.swing.GroupLayout(jPanelClienteTotal);
        jPanelClienteTotal.setLayout(jPanelClienteTotalLayout);
        jPanelClienteTotalLayout.setHorizontalGroup(
            jPanelClienteTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        jPanelClienteTotalLayout.setVerticalGroup(
            jPanelClienteTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteTotalLayout.createSequentialGroup()
                .addComponent(jpCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Contatos Cliente", jPanelClienteTotal);

        jpFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Fornecedor*"));

        jLabel19.setText("Razão Social:");

        tfRazaoSocial.setEditable(false);

        tfCNPJForn.setEditable(false);

        jLabel21.setText("CNPJ:");

        tfEnderecoForn.setEditable(false);

        jLabel22.setText("Endereço:");

        jLabel23.setText("Telefone:");

        tfTelefoneForn.setEditable(false);

        tfBairroForn.setEditable(false);

        jLabel24.setText("Bairro:");

        tfCidadeForn.setEditable(false);

        jLabel25.setText("Cidade:");

        btPFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/procurar_20x20.png"))); // NOI18N
        btPFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFornecedorLayout = new javax.swing.GroupLayout(jpFornecedor);
        jpFornecedor.setLayout(jpFornecedorLayout);
        jpFornecedorLayout.setHorizontalGroup(
            jpFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFornecedorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpFornecedorLayout.createSequentialGroup()
                        .addGroup(jpFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel19))
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jpFornecedorLayout.createSequentialGroup()
                                    .addComponent(tfBairroForn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfCidadeForn, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFornecedorLayout.createSequentialGroup()
                                    .addComponent(tfRazaoSocial)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btPFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfEnderecoForn))
                            .addGroup(jpFornecedorLayout.createSequentialGroup()
                                .addComponent(tfCNPJForn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTelefoneForn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(305, 305, 305))))
        );
        jpFornecedorLayout.setVerticalGroup(
            jpFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(tfRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCNPJForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)
                        .addComponent(tfTelefoneForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEnderecoForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(tfBairroForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfCidadeForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Descrição Contato", "Tipo", "Pessoa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFornecedorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbFornecedor);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jpFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Contatos Fornecedor", jPanel3);

        jPanelFuncTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanelFuncTotalFocusGained(evt);
            }
        });

        tbFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Descrição Contato", "Tipo", "Pessoa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbFuncionario);

        jpFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Funcionário"));

        jLabel16.setText("Nome:");

        tfNomeFunc.setEditable(false);

        tfRGFunc.setEditable(false);

        jLabel18.setText("RG:");

        tfFuncaoFunc.setEditable(false);

        jLabel26.setText("Função:");

        jLabel27.setText("Telefone:");

        tfTelefoneFunc.setEditable(false);

        tfLoginFunc.setEditable(false);

        jLabel28.setText("Login:");

        btPFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/procurar_20x20.png"))); // NOI18N
        btPFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPFuncionarioActionPerformed(evt);
            }
        });

        jLabel30.setText("CPF:");

        tfCPFFunc.setEditable(false);

        javax.swing.GroupLayout jpFuncionarioLayout = new javax.swing.GroupLayout(jpFuncionario);
        jpFuncionario.setLayout(jpFuncionarioLayout);
        jpFuncionarioLayout.setHorizontalGroup(
            jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFuncionarioLayout.createSequentialGroup()
                        .addComponent(tfNomeFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jpFuncionarioLayout.createSequentialGroup()
                        .addComponent(tfRGFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCPFFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTelefoneFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFuncionarioLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(tfFuncaoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfLoginFunc))))
        );
        jpFuncionarioLayout.setVerticalGroup(
            jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFuncionarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(tfNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfRGFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27)
                        .addComponent(tfTelefoneFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfCPFFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30))
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(jpFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfFuncaoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28)
                        .addComponent(tfLoginFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106))
        );

        btAdicionarFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ok.png"))); // NOI18N
        btAdicionarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarFuncActionPerformed(evt);
            }
        });

        cbTipoFunc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTipoFunc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoFuncItemStateChanged(evt);
            }
        });

        jLabel1.setText("Tipo Contato*:");

        btExcluirFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/bExcluir.png"))); // NOI18N
        btExcluirFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirFuncActionPerformed(evt);
            }
        });

        jLabel2.setText("Descrição*:");

        javax.swing.GroupLayout jpContatoFuncLayout = new javax.swing.GroupLayout(jpContatoFunc);
        jpContatoFunc.setLayout(jpContatoFuncLayout);
        jpContatoFuncLayout.setHorizontalGroup(
            jpContatoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContatoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpContatoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfDescricaoContatoFunc)
                    .addComponent(cbTipoFunc, 0, 161, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btAdicionarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluirFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jpContatoFuncLayout.setVerticalGroup(
            jpContatoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContatoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btExcluirFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpContatoFuncLayout.createSequentialGroup()
                        .addGroup(jpContatoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTipoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpContatoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAdicionarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpContatoFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfDescricaoContatoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFuncTotalLayout = new javax.swing.GroupLayout(jPanelFuncTotal);
        jPanelFuncTotal.setLayout(jPanelFuncTotalLayout);
        jPanelFuncTotalLayout.setHorizontalGroup(
            jPanelFuncTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
            .addComponent(jpFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelFuncTotalLayout.createSequentialGroup()
                .addComponent(jpContatoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelFuncTotalLayout.setVerticalGroup(
            jPanelFuncTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFuncTotalLayout.createSequentialGroup()
                .addComponent(jpFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpContatoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Contatos Funcionário", jPanelFuncTotal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFechar1ActionPerformed
        dispose();
    }//GEN-LAST:event_btFechar1ActionPerformed

    private void jPanelClienteTotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelClienteTotalFocusGained

    }//GEN-LAST:event_jPanelClienteTotalFocusGained

    private void tbFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFuncionarioMouseClicked

    }//GEN-LAST:event_tbFuncionarioMouseClicked

    private void jPanelFuncTotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelFuncTotalFocusGained

    }//GEN-LAST:event_jPanelFuncTotalFocusGained

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        limpaCampos();
        habilitaCamposCliente(false);
        habilitaCamposFornecedor(false);
        habilitaCamposFuncionario(false);

        if (jTabbedPane1.getSelectedIndex() == 1) {

        } else if (jTabbedPane1.getSelectedIndex() == 0) {

        } else if (jTabbedPane1.getSelectedIndex() == 2) {

        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained

    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void btPClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPClienteActionPerformed
        DgConsultaCliente tela = new DgConsultaCliente(null, null, this);
        tela.setVisible(true);
    }//GEN-LAST:event_btPClienteActionPerformed

    private void btPFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPFornecedorActionPerformed
        DgConsultaFornecedor tela = new DgConsultaFornecedor(null, this);
        tela.setVisible(true);
    }//GEN-LAST:event_btPFornecedorActionPerformed

    private void btPFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPFuncionarioActionPerformed
        DgConsultaFuncionario tela = new DgConsultaFuncionario(null, null, null, this);
        tela.setVisible(true);
    }//GEN-LAST:event_btPFuncionarioActionPerformed

    private void tbClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbClienteMouseClicked

    private void tbFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFornecedorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbFornecedorMouseClicked

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed

        btNovo.setEnabled(false);
        btSalvar.setEnabled(true);
        if (jTabbedPane1.getSelectedIndex() == 0) {
            habilitaCamposCliente(true);

        }
        if (jTabbedPane1.getSelectedIndex() == 1) {
            habilitaCamposFornecedor(true);

        }
        if (jTabbedPane1.getSelectedIndex() == 2) {
            habilitaCamposFuncionario(true);

        }


    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (tfBairroCli.getText().trim().length() > 0) {

        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios!");
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btAdicionarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarFuncActionPerformed

        Object[] object;
        Pessoa pessoa = new Pessoa();
        object = (Object[]) Popula.retornaDadosPessoas(codFuncionario);
        List<Funcionario> lf = (List<Funcionario>) object[4];
        for (Funcionario linf : lf) {
            pessoa = linf.getPessoa();
        }
        Contato contato = new Contato();
        contato.setIdcontato(0);
        contato.setDescricao(tfDescricaoContatoFunc.getText());
        contato.setPessoa(pessoa);

        ComboItens cbit = (ComboItens) cbTipoFunc.getSelectedItem();

        int idTipoContato = cbit.getCodigo();

        Object[] objectt;
        objectt = (Object[]) Popula.retornaTipoContato(idTipoContato);
        List<Tipocontato> list = (List<Tipocontato>) objectt[0];
        for (Tipocontato lin : list) {
            Tipocontato tc = lin;
            contato.setTipocontato(tc);
            DAO.salvarContato(contato, "salvar");
        }
        habilitaCamposFuncionario(false);
    }//GEN-LAST:event_btAdicionarFuncActionPerformed

    private void btExcluirFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirFuncActionPerformed
        if (tbFuncionario.getRowCount() > 1) {
            if (tbFuncionario.getSelectedRow() >= 0) {
                Object[] options = {" Sim ", " Não "};
                String descricao = String.valueOf(tbFuncionario.getValueAt(tbFuncionario.getSelectedRow(), 1));
                int opcaoExcluir = JOptionPane.showOptionDialog(this.getContentPane(), "Deseja excluir o Contato "
                        + descricao + "?",
                        "Informação", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[1]);

                if (opcaoExcluir == 0) {
                    int id = (int) tbFuncionario.getValueAt(tbFuncionario.getSelectedRow(), 0);
                    System.out.println("id a ser excluido:" + id);
                    if (DAO.deletarContato(id)) {
                        JOptionPane.showMessageDialog(null, "Contato excluído!");
                        Popula.popularTabelaContatos(codFuncionario, "", tbFuncionario);
                    } else {
                        JOptionPane.showMessageDialog(null, "Problemas ao excluir");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione algum registro!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "É obrigatório ter um contato cadastrado!");
        }
    }//GEN-LAST:event_btExcluirFuncActionPerformed

    private void cbTipoFuncItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoFuncItemStateChanged
       if(cbTipoFunc.getSelectedItem() == "Telefone"){
           Formatacao.reformatarTelefone(tfDescricaoContatoFunc);
       }else{
           tfDescricaoContatoFunc.setText("");
       }
    }//GEN-LAST:event_cbTipoFuncItemStateChanged

    public void defineCodigoFuncionario(int cod) {
        codFuncionario = cod;
        Popula.popularTabelaContatos(codFuncionario, "", tbFuncionario);

        JTable aux = new JTable();
        List<Populartabelafuncionario> l = Popula.popularTabelaFuncionario(cod, String.valueOf(cod), aux);
        for (Populartabelafuncionario lin : l) {
            tfNomeFunc.setText(lin.getNome());
            tfRGFunc.setText(lin.getRg());
            tfCPFFunc.setText(lin.getCpf());
            tfTelefoneFunc.setText(lin.getDescricaocontato());
            tfFuncaoFunc.setText(lin.getDescricaofuncao());
            tfLoginFunc.setText(lin.getLogin());
        }
    }

    public void defineCodigoFornecedor(int cod) {
        codFornecedor = cod;
        Popula.popularTabelaContatos(codFornecedor, "", tbFornecedor);

        JTable aux = new JTable();
        List<Populartabelafornecedor> dadosForn = Popula.popularTabelaFornecedor(cod, String.valueOf(cod), aux);
        for (Populartabelafornecedor lin : dadosForn) {
            tfRazaoSocial.setText(lin.getNome());
            tfCNPJForn.setText(lin.getCnpj());
            tfTelefoneForn.setText(lin.getDescricaocontato());
            tfEnderecoForn.setText(lin.getDescricaoendereco());
            tfBairroForn.setText(lin.getBairro());
            tfCidadeForn.setText(lin.getDescricaocidade());
        }

    }

    public void defineCodigoCliente(int cod) {
        codCliente = cod;
        Popula.popularTabelaContatos(codCliente, "", tbCliente);

        JTable aux = new JTable();
        List<Populartabelacliente> l = Popula.popularTabelaCliente(cod, String.valueOf(cod), aux);
        for (Populartabelacliente lin : l) {
            tfNomeCliente.setText(lin.getNome());
            tfRGCli.setText(lin.getRg());
            tfCPFCli.setText(lin.getCpf());
            tfTelefoneCli.setText(lin.getDescricaocontato());
            tfEnderecoCli.setText(lin.getDescricaoendereco());
            tfBairroCli.setText(lin.getBairro());
            tfCidadeCli.setText(lin.getDescricaocidade());
        }
    }

    public void limpaCampos() {

        limpaCampos lv = new limpaCampos();
        lv.limparCampos(jpCliente);
        lv.limparCampos(jpFornecedor);
        lv.limparCampos(jpFuncionario);
        lv.limparCampos(jpContatoFunc);
        populaCombos();
        cbTipoFunc.setSelectedIndex(0);
        tbCliente.removeAll();
        tbFornecedor.removeAll();
        tbFuncionario.removeAll();
    }

    private void habilitaCamposCliente(boolean tf) {
        if (tf == false) {
            limpaCampos();
            btSalvar.setEnabled(false);
            btNovo.setEnabled(true);
        }
        Popula.popularTabelaContatos(codCliente, "", tbCliente);
        btPCliente.setEnabled(tf);

    }

    private void habilitaCamposFornecedor(boolean tf) {
        if (tf == false) {
            limpaCampos();
            btSalvar.setEnabled(false);
            btNovo.setEnabled(true);
        }
        Popula.popularTabelaContatos(codFornecedor, "", tbFornecedor);
        btPFornecedor.setEnabled(tf);
    }

    private void habilitaCamposFuncionario(boolean tf) {
        if (tf == false) {
            limpaCampos();
            btSalvar.setEnabled(false);
            btNovo.setEnabled(true);
        }
        Popula.popularTabelaContatos(codFuncionario, "", tbFuncionario);
        btPFuncionario.setEnabled(tf);
        btAdicionarFunc.setEnabled(tf);
        btExcluirFunc.setEnabled(tf);
        tfDescricaoContatoFunc.setEnabled(tf);
        cbTipoFunc.setEnabled(tf);
    }

    public void populaCombos() {
        cbTipoFunc.removeAllItems();
        new CombosDAO().popularCombo("Tipocontato", "idtipoContato", "descricao", cbTipoFunc, "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarFunc;
    private javax.swing.JButton btExcluirFunc;
    private javax.swing.JButton btFechar1;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPCliente;
    private javax.swing.JButton btPFornecedor;
    private javax.swing.JButton btPFuncionario;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbTipoFunc;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelClienteTotal;
    private javax.swing.JPanel jPanelFuncTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel jpCliente;
    private javax.swing.JPanel jpContatoFunc;
    private javax.swing.JPanel jpFornecedor;
    private javax.swing.JPanel jpFuncionario;
    private javax.swing.JTable tbCliente;
    private javax.swing.JTable tbFornecedor;
    private javax.swing.JTable tbFuncionario;
    private javax.swing.JTextField tfBairroCli;
    private javax.swing.JTextField tfBairroForn;
    private javax.swing.JTextField tfCNPJForn;
    private javax.swing.JTextField tfCPFCli;
    private javax.swing.JTextField tfCPFFunc;
    private javax.swing.JTextField tfCidadeCli;
    private javax.swing.JTextField tfCidadeForn;
    private javax.swing.JFormattedTextField tfDescricaoContatoFunc;
    private javax.swing.JTextField tfEnderecoCli;
    private javax.swing.JTextField tfEnderecoForn;
    private javax.swing.JTextField tfFuncaoFunc;
    private javax.swing.JTextField tfLoginFunc;
    private javax.swing.JTextField tfNomeCliente;
    private javax.swing.JTextField tfNomeFunc;
    private javax.swing.JTextField tfRGCli;
    private javax.swing.JTextField tfRGFunc;
    private javax.swing.JTextField tfRazaoSocial;
    private javax.swing.JTextField tfTelefoneCli;
    private javax.swing.JTextField tfTelefoneForn;
    private javax.swing.JTextField tfTelefoneFunc;
    // End of variables declaration//GEN-END:variables
}
